[package]
name = "monkebucko"
version = "0.1.0"
edition = "2024"
authors = ["Scup st.chrysops@gmail.com"]


[dependencies]
bevy = {version = "0.16", features = ["serialize"]}
serde = "1.0.219"
bevy-persistent = { version = "0.8.0", features = ["toml"] }
# bevy_text_animation = "0.4.1"
# vleue_kinetoscope = "0.4.1"